### ISSUE TITLE
Away mode

### ISSUE THREAD

**Issue by henryouly** [henryouly/homeassistant-config#7]
```
- platform: template
  sensors:
     upstairs_away_mode:
       entity_id: climate.upstairs
       value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"

- platform: template
  sensors:
     downstairs_away_mode:
       entity_id: climate.downstairs
       value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"
```

**Comment by henryouly** [comment]
```

- alias: 'Upstairs Light Turn on'
  trigger:
    - platform: event
      event_type: upstairs_light_on
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      to: 'off'
  
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      before: '23:45'
      
  action:
    service: light.turn_on
    entity_id: group.upstairs

- alias: 'Upstairs Light Turn off'
  trigger:
    - platform: event
      event_type: upstairs_light_off
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      to: 'on'
        
  action:
    service: light.turn_off
    entity_id: group.upstairs
```
